### ISSUE TITLE
"scmap" not resolved

### ISSUE THREAD

**Issue by sourav-majumdar-math** [dewittpe/sccm#14]
`> mce <- sccm::d2p(CircleLimitI[, c("x", "y")])`

`Error in .C("scmap_", n = as.integer(n), w = as.double(w), wc = as.double(wc),  : 
  "scmap_" not resolved from current namespace (sccm)`

Hi, I get the following error when I try to run d2p. I would be grateful if you could guide me here.

**Comment by dewittpe** [comment]
Solution to this issue is currently in the `dev` branch of this repository.

Install the dev version via:

```r
remotes::install_github("dewittpe/sccm@dev")
```

The fix was provided by this [StackOverflow Answer](https://stackoverflow.com/a/51394448/1104685)

**Comment by dewittpe** [comment]
Duplicate of #12
